linters:
  enable:
    - gofmt
    - gocyclo
    - golint
    - misspell
    - typecheck
    - typecheck
    - errcheck
run:
  skip-dirs:
    - modelplugin

issues:
  exclude-rules:
    - path: pkg/client/map
      linters:
        - golint
    - path: pkg/client/lock/options.go
      linters:
        - golint